# Generated by Django 4.0.5 on 2022-06-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('ArtId', models.AutoField(primary_key=True, serialize=False)),
                ('Artist_Name', models.CharField(max_length=50)),
                ('Artist_DOB', models.DateField()),
                ('Artist_Bio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Song_Name', models.CharField(max_length=50)),
                ('Rating', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('SngId', models.AutoField(primary_key=True, serialize=False)),
                ('Song_Name', models.CharField(max_length=50)),
                ('Song_DOR', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Songs_Artists',
            fields=[
                ('saId', models.AutoField(primary_key=True, serialize=False)),
                ('Song_Name', models.CharField(max_length=50)),
                ('Artist_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
    ]
